### ISSUE TITLE
TDK ICS-41352 PDM mic

### ISSUE THREAD

**Issue by ohnowhathaveidone** [GrahamM/ESP32_I2S_Microphone#1]
Hi @GrahamM ,  

First of all, thanks a lot for your work on this - it really pushed me a good bit forward with TDK's ICS-41352 microphones. After a few tweaks, I seem to be getting very good performance out of them. 

This is more of a comment than an issue: my mics are supposed to be sampled with a maximum frequency of 4.8 MHz. Above that, I was only getting noise back. With your setup, I was effectively only capable to go up to 72 kHz sampling rate. What helped me, was setting `fixed_mclk` in the I2S configuration: 
``` C    
static const i2s_config_t i2s_config = { 
        .mode = I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_PDM, 
        .sample_rate = 192000,  
        .bits_per_sample = 32,  
        .channel_format = I2S_CHANNEL_FMT_ALL_LEFT,  // I only use one mic
        .communication_format = I2S_COMM_FORMAT_STAND_MSB, 
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,     
        .dma_buf_count = 4,                            
        .dma_buf_len = BLOCK_SIZE,                     
        .use_apll = 1, //<-NEW
        .fixed_mclk = 124000000, //<-NEW 
};
```

With this setup, I seem to get very clean audio at 192 kHz. But I still need to do the math, if I'm overlapping samples here or if I'm doing something else that's stupid. There's a few other tweaks that are related to a newer version of the I2S driver, I believe. Also, I was clocking my mics via the WS pin. This doesn't make much sense to me, but it worked better. 

And as a last difference, I was using ESP IDF, rather than Arduino IDE. 

Again, this is more of a comment, so feel free to ignore this. But I guess it would be interesting to see if fixing the clock speed does any change on the noise levels of your mics at higher sampling rates. 

Thanks for your work again!
Cheers!

**Comment by GrahamM** [comment]
Thanks for this info @ohnowhathaveidone. I'd like to spend a little time figuring out what the impact of your changes are, and how that changes the clocking. I'm definitely going to give this a go in order to see if it changes the noise floor at all.

**Comment by GrahamM** [comment]
I had to go back and re-read some of the ESP32 technical reference manual while getting my head around this.  My understanding is that the PDM receive module uses a filter group to downsample the PDM signal. The filter group can operate at /64 or /128 based on I2S_RX_PDM_SINC_DSR_16_EN bit of register I2S_PDM_CONF_REG. My code operates at /64, so every 64 bits from the PDM microphone will result in a single PCM sample. 

So, with the original code and a 192KHz sample rate, the clock is running at about 12.28MHz (validated with an oscilloscope). That would be in the ballpark of what I expected, as we're clocking 64bits for each PCM sample.
Switching in the use_apll and fixed_mclk, I'm seeing a clock of about 6MHz. That would suggest that you're actually getting data at about 93.75KHz. It might be worth measuring how quickly samples are coming in perhaps?

I haven't switched the sample over to ESP IDF however. That might have an impact, although I would be surprised if it did.

**Comment by ohnowhathaveidone** [comment]
Yeah, I did a little math myself yesterday and my approach definitely can't give me 192 kHz at 64 bit wide samples. But I'm also struggling a bit with packet loss via the UDP connection, which contributes to choppy sound. So there's still a few things for me to resolve. I've had the feeling with the docs that they don't necessarily mention, what certain options do exactly, so there's a good amount of trial and error. 
I only had an analog scope available that's not too fancy, so it was hard to tell what exact frequency I was actually clocking the mic with. However, my experience has been that as soon as I clock too fast, there's only garbage coming back on the data line and then all I record is noise. 
And no - switching to ESP IDF should make no big difference. The IDF exposes more from freeRTOS than the Arduino IDE, giving you more fine grained control. And the monitoring mode is pretty neat for logging. 
I can push my code to GH somewhen around today for comparison.

**Comment by ohnowhathaveidone** [comment]
I dumped my version [here](https://github.com/ohnowhathaveidone/ESP32_PDM_MIC)  
Code is still very much work in progress, so it's probably terrible in many places.

**Comment by ohnowhathaveidone** [comment]
Hi @GrahamM , 
Quick update from my side: It seems to me like my microphone just isn't to well suited to run with an ESP32. Technically, it should deliver data at 200 kHz sampling rate with 25 bits per sample and the clock running at 4.8 MHz. This set of parameters just doesn't seem to add up with the I2S driver. I either get only noise in my signal or the UDP server doesn't manage to send data in time.  

I still find the I2S driver configuration somewhat confusing. One detail in my configuration is that I added `I2S_MODE_PDM` to `.mode`. This seemed like a natural choice, but according to documentation, this mode clocks the mic via the WS line. Bitclock just remains low. This doesn't make much sense to me. On top of that, `.channel_format` seemed to have absolutely no influence. 

Either way, I have version that seems to work for me now - I get around 100 kHz sampling rate at 16 bit, which will be fine for my application. Latest code is in the repo linked above. 

I'll probably try to do a few more tests in the future.

**Comment by GrahamM** [comment]
The microphone delivers PDM data, which is a high-speed 1-bit format (from the sigma-delta converter). Obviously, you're getting PCM data out of the I2S interface, so there's a bit of conversion going on inside the ESP32 for you. It is possible to convert PDM data to various bitrates/sample depths through a filter and decimate process. This is what the ESP32 is doing, but its filters are pretty fixed. If you are happy to try to do the conversion yourself it is possible to have higher sampling rates if you're happy to drop the bit-depth, and vise versa - it's a tradeoff. Two of the more useful articles I've come across is at [https://curiouser.cheshireeng.com/2014/11/04/using-a-pdm-microphone/](https://curiouser.cheshireeng.com/2014/11/04/using-a-pdm-microphone/)  and [https://tomverbeure.github.io/2020/10/04/PDM-Microphones-and-Sigma-Delta-Conversion.html](https://tomverbeure.github.io/2020/10/04/PDM-Microphones-and-Sigma-Delta-Conversion.html)

I hope this helps, as there's much more to things than it first appears!

**Comment by ohnowhathaveidone** [comment]
Thanks for the links! I think I ran into both when I was looking at how to use the microphones. The concept makes sense to me and probably I've been messing up the terminology quite a bit. 

I was pondering with the idea to do this on an FPGA with the Alchitry boards I have to get a proper idea of how they work, but the task of getting the data to my PC scared me off. ESP32 seemed like a more convenient option. I need this for work after all, so I need to be somewhat efficient (by working in research standards). 

Again, I just find Espressif's driver for interfacing PDM mics somewhat confusing.

**Comment by ohnowhathaveidone** [comment]
Alright, one last comment from my side :) 

I got the setup to work in a way that I'm happy with and that largely makes sense to me. I'll still have to check on the docs a bit. 

I'll close this issue, as it isn't a problem with your code anyway. 

Thanks a lot for your support!
